/* tslint:disable */
/* eslint-disable */
/**
 * Room Booking Service
 * Innopolis University room booking service API.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BookRoomRequest
 */
export interface BookRoomRequest {
    /**
     * 
     * @type {any}
     * @memberof BookRoomRequest
     */
    title: any | null;
    /**
     * 
     * @type {any}
     * @memberof BookRoomRequest
     */
    start: any | null;
    /**
     * 
     * @type {any}
     * @memberof BookRoomRequest
     */
    end: any | null;
}

/**
 * Check if a given object implements the BookRoomRequest interface.
 */
export function instanceOfBookRoomRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "title" in value;
    isInstance = isInstance && "start" in value;
    isInstance = isInstance && "end" in value;

    return isInstance;
}

export function BookRoomRequestFromJSON(json: any): BookRoomRequest {
    return BookRoomRequestFromJSONTyped(json, false);
}

export function BookRoomRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): BookRoomRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'title': json['title'],
        'start': json['start'],
        'end': json['end'],
    };
}

export function BookRoomRequestToJSON(value?: BookRoomRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
        'start': value.start,
        'end': value.end,
    };
}

