/* tslint:disable */
/* eslint-disable */
/**
 * Room Booking Service
 * Innopolis University room booking service API.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetFreeRoomsRequest
 */
export interface GetFreeRoomsRequest {
    /**
     * 
     * @type {any}
     * @memberof GetFreeRoomsRequest
     */
    start: any | null;
    /**
     * 
     * @type {any}
     * @memberof GetFreeRoomsRequest
     */
    end: any | null;
}

/**
 * Check if a given object implements the GetFreeRoomsRequest interface.
 */
export function instanceOfGetFreeRoomsRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "start" in value;
    isInstance = isInstance && "end" in value;

    return isInstance;
}

export function GetFreeRoomsRequestFromJSON(json: any): GetFreeRoomsRequest {
    return GetFreeRoomsRequestFromJSONTyped(json, false);
}

export function GetFreeRoomsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetFreeRoomsRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'start': json['start'],
        'end': json['end'],
    };
}

export function GetFreeRoomsRequestToJSON(value?: GetFreeRoomsRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'start': value.start,
        'end': value.end,
    };
}

