/* tslint:disable */
/* eslint-disable */
/**
 * Room Booking Service
 * Innopolis University room booking service API.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface QueryBookingsRequest
 */
export interface QueryBookingsRequest {
    /**
     * Only bookings that ended before this time are returned.
     * @type {any}
     * @memberof QueryBookingsRequest
     */
    endedAfter: any | null;
    /**
     * Only bookings that started before this time are returned.
     * @type {any}
     * @memberof QueryBookingsRequest
     */
    startedBefore: any | null;
    /**
     * When specified, only bookings of the rooms from the list will be returned.
     * @type {any}
     * @memberof QueryBookingsRequest
     */
    roomIdIn?: any | null;
    /**
     * When specified, only bookings with the owner with email address from the list will be returned.
     * @type {any}
     * @memberof QueryBookingsRequest
     */
    ownerEmailIn?: any | null;
}

/**
 * Check if a given object implements the QueryBookingsRequest interface.
 */
export function instanceOfQueryBookingsRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "endedAfter" in value;
    isInstance = isInstance && "startedBefore" in value;

    return isInstance;
}

export function QueryBookingsRequestFromJSON(json: any): QueryBookingsRequest {
    return QueryBookingsRequestFromJSONTyped(json, false);
}

export function QueryBookingsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): QueryBookingsRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'endedAfter': json['ended_after'],
        'startedBefore': json['started_before'],
        'roomIdIn': !exists(json, 'room_id_in') ? undefined : json['room_id_in'],
        'ownerEmailIn': !exists(json, 'owner_email_in') ? undefined : json['owner_email_in'],
    };
}

export function QueryBookingsRequestToJSON(value?: QueryBookingsRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ended_after': value.endedAfter,
        'started_before': value.startedBefore,
        'room_id_in': value.roomIdIn,
        'owner_email_in': value.ownerEmailIn,
    };
}

